# Generated by Django 4.2.5 on 2023-09-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_board_img_url_board_update_date_board_upload_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
