# Generated by Django 4.2.5 on 2023-09-14 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_category_user_remove_board_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='upload_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='category_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
