# Generated by Django 4.2.5 on 2023-09-14 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_board_upload_date_alter_board_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='board',
            name='upload_date',
        ),
    ]
